export let Annonce = [
    {id:1,
        nom_annonce:"FORFAIT CODE + CONDUITE" ,
        description : "Forfait code illimité 6 mois,Frais d accompagnement au permis" ,
        prix :"450D" , 
        image :"asset/images/news-01.jpg" ,
        date_debut :    new Date('02/21/2019') ,
        date_fin : new Date('03/05/2019') ,
        
        is_new :   true},
    {id:2,
     nom_annonce:"FORFAIT CODE SEUL" ,
    description :"Forfait code illimité 6 mois" ,
    prix :  "250D" , 
    image :"asset/images/news-02.jpg" ,
    date_debut :       new Date('02/22/2019') , 
    date_fin :new Date('04/26/2019') ,
    is_new :   true},
    {id:3,
        nom_annonce:"FORFAIT CONDUITE SEULE" ,
        description : "valuation obligatoire (45 minutes),20 leçons de conduite,Fourniture pédagogique" ,
        prix : "500D" , 
        image :"asset/images/news-03.jpg" ,
        date_debut :   new Date('02/21/2019') , 
        date_fin :new Date('05/25/2019') ,
        is_new :   true},
        {id:4,
            nom_annonce:"FORFAIT CONDUITE SEULE" ,
            description : "validation obligatoire (45 minutes),20 leçons de conduite,Fourniture pédagogique" ,
            prix : "800D" , 
            image :"asset/images/news-03.jpg" ,
            date_debut :   new Date('02/21/2019') , 
            date_fin :new Date('05/25/2019') ,
            is_new :   true},
            {id:5,
                nom_annonce:"FORFAIT CONDUITE SEULE" ,
                description : "validation obligatoire (45 minutes),20 leçons de conduite,Fourniture pédagogique" ,
                prix : "500D" , 
                image :"asset/images/news-03.jpg" ,
                date_debut :   new Date('02/21/2019') , 
                date_fin :new Date('05/25/2019') ,
                is_new :   true}
  ];